spring.application.name=tarea4

spring.datasource.url=jdbc:mysql://localhost:3306/tarea2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=cc5002
spring.datasource.password=programacionweb

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.port=8080
